# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 941bcce616fe05cb51f497d5032e619bf975acb7051a047a9ecb7a23568f5cc4b46a8dd04cb87bd5ef78a644afc3f07a5c6942d61fa9f16e4fe3ccaf22c5bb0e

test:
  secret_key_base: 56d0161c6dc81c01b60eab2c0c450fae7e4959ac8b6e0426c34650a520bfa68d8c1c99199344d9dc4e044fd6acb110511f16e289434003f889f139656152f640

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
